url: http://10.16.6.191:7997/embedding
headers:
  Authorization: "Bearer sk-7b8a2c88-8a6b-416d-8502-83298d40a5aa"
  Content-Type: 'application/json'
  Accept: 'application/json'
data:
  model: "models/bge-large-zh-v1.5"
  encoding_format: "float"
  user: "string"
  dimensions: 1024
